// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    contract
    (
        init => init
        upgrade => upgrade
        call_call_bt => call_call_bt
        call_bt_call_bt => call_bt_call_bt
        call_send_back_async_v1 => call_send_back_async_v1
        call_send_back_async_v2 => call_send_back_async_v2
        send_back => send_back
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
